### ISSUE TITLE
Link to github

### ISSUE THREAD

**Issue by fischmalte** [mad-lab-fau/imucal#10]
If one googles for ferraris calibration, one easily gets to readthedocs and reads about github page or github-issue. To make it easier to get there, the text passages in the README.md could become a link.

**Comment by AKuederle** [comment]
Good idea! Could you add that? Btw. in the top right of the docu page is a link to the github repo

**Comment by fischmalte** [comment]
oh that's somewhat quite far away I admit I did not search there 😁 Should I add that by opening a new pull request? 🤔

**Comment by fischmalte** [comment]
handled in #12
