### ISSUE TITLE
Review JOSS

### ISSUE THREAD

**Issue by tuliofalmeida** [mad-lab-fau/imucal#18]
This is an issue created as part of [imucal - JOSS Review](https://github.com/openjournals/joss-reviews/issues/4338)

Hi,

I tested the library (pypi version) by running the examples and on own data and it worked fine. The documentation is also well done. I have only one suggestion to expand the scope and use by other laboratories.

Would it be possible to create a version to work in server/Jupyter ? I believe that if this information can be passed through a dictionary based on the index of each moment, in this way it could be integrated with other applications and increase the impact of the work. The user would plot the data and extract the times himself.

Best,

Túlio

**Comment by AKuederle** [comment]
Hi Túlio,

thanks for the feedback! I am not 100% sure if I understand your suggestion correctly.

1. Would it be possible to create a version in server/Jupyter?
The library works perfectly fine on the server or on Jupyter. Only the GUI works only locally, as it uses a local GUI toolkit. If you have the timings already or recorded the different calibration phases as different recordings you can use [ferraris_regions_from_df](https://imucal.readthedocs.io/en/latest/modules/generated/imucal.ferraris_regions_from_df.html) or [ferraris_regions_from_section_list](https://imucal.readthedocs.io/en/latest/modules/generated/imucal.ferraris_regions_from_section_list.html) (or create some custom way to create a `FerrarisSignalRegions` object) to initialize the calibration.

Then you can use the library just fine in Jupyter or on a server, or in a another library (that is what we are doing internally as well).
Is that what you meant? If yes, I will make sure that it is clear in the README, that you do not need to use the GUI to find the different sections.

**Comment by tuliofalmeida** [comment]
Perfect, that was exactly it. I had only tested it on my own pc and reading the repository I had understood that it was in general. 
I had already given the report of my review. Thanks.

**Comment by AKuederle** [comment]
Will keep it open until I modified the README accordingly to make that clearer :)

**Comment by AKuederle** [comment]
I have changed the README in 127054ba22ab211f72e97b868b89596c542b1e2d .

I will close the issue, but feel free to reopen, if you think the change is not sufficient.
