### ISSUE TITLE
[JOSS REVIEW] - Add link to documentation

### ISSUE THREAD

**Issue by finsberg** [mad-lab-fau/imucal#19]
Congratulations on this very nice code base.

I am missing a clear way to get to the documentation page, i.e <https://imucal.readthedocs.io/en/latest/README.html>.
I think it would be good to either add a section for this in the README and / or add the link in the sidebar

**Comment by AKuederle** [comment]
Hi Henrick! Thank you very much for your feedback. We have the Docu batch that is clickable, but I agree that is not really discoverable. I will add a proper link as part of the README.

**Comment by AKuederle** [comment]
This has been addressed in 127054ba22ab211f72e97b868b89596c542b1e2d .
I will close the issue, but feel free to reopen it, if you don't thing the change is sufficient.

**Comment by AKuederle** [comment]
Just to track the issue as part of the review: https://github.com/openjournals/joss-reviews/issues/4338
