### ISSUE TITLE
Calibration data

### ISSUE THREAD

**Issue by Aleja-C** [mad-lab-fau/imucal#23]
I would like to use the calibration library that you propose for minImu-9 v5 sensor, only with accelerometer and gyroscope, my question is if the data obtained from the calibration can be used later in data obtained in real time and apply the calibration there and how can it be done?

**Comment by AKuederle** [comment]
Hi Aleja this really depends on your usecase. You can use the library to create your calbration. A calibration is "just" a couple of matrices that you can export to a json file to be used later.

You can use the functions from this library to apply the calibrations to new data if your code is written in Python. We usually do that after we recorded the data, but you should be able to do it "live" as well (depending on the speed of new samples). If your "live" code is not written in Python, you can still use the matrices, but you would need to reimplement the code to apply the matrices. But these are relatively simply calculations:

You can find the required steps in this file: https://github.com/mad-lab-fau/imucal/blob/master/imucal/ferraris_calibration_info.py

**Comment by AKuederle** [comment]
@Aleja-C I will close this issue for now. Feel free to reopen, in case you have further questions.
