### ISSUE TITLE
Link literature

### ISSUE THREAD

**Issue by fischmalte** [mad-lab-fau/imucal#9]
Suggestion: Add link to readme at the top , where supported methods are listed

https://www.sciencedirect.com/science/article/pii/0924424794800316

**Comment by AKuederle** [comment]
Pull request welcome :) I am still annoyed that you can not find the full text version of the paper anywher anymore....

**Comment by AKuederle** [comment]
Oh wait! You link actually has the fulltext! How did you find that? :D

**Comment by fischmalte** [comment]
I googled, but it was a bit hidden somehow, so not obviously the first entry or so :D

**Comment by fischmalte** [comment]
handling this in #12
